# Generated by Django 5.1.6 on 2025-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Emails', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
